### ISSUE TITLE
Incorrect usage of System.Random

### ISSUE THREAD

**Issue by axman6** [folivetti/HBLCoClust#3]
I was having a look over the code for your LHS implementation and noticed you're using StdGen incorrectly on https://github.com/folivetti/HBLCoClust/blob/24cc921bd3a18a684658d5fae27b1d62d2c00d11/Haskell/src/lsh.hs#L70. The way it's used here will mean that both `n1` and `n2` are identical because the StdGen inouts is identical, which will probably lead to some strange results -  to fix this you should split the StdGen:

```haskell
...
      (g1,g2) = split g
      n1 = take (r*b) (randomRs (1, largeprime-1) g1)
      n2 = take (r*b) (randomRs (1, largeprime-1) g2)
```

**Comment by folivetti** [comment]
indeed! It was incorrect! Thank you very much for the correction :-)
I have to take some time to rewrite this code now that I'm a little bit more experienced in Haskell.

**Comment by axman6** [comment]
Thanks for the quick fix! It'd be great to see the code updated, it feels very much like the code I would have written when I was new to Haskell too. We may have a use for this in the next few months so would be keen to see this as a usable (preferably high performance) library - if we do end up using it I would be interested in contributing to the project.

**Comment by folivetti** [comment]
It's gonna take some time for me to go back to this code (but hopefully soon enough). It'd be great to get some help to this project. I'm very interested on how and why you're using this algorithm!
